### ISSUE TITLE
Some issues while running Mayavi on Qt5

### ISSUE THREAD

**Issue by prabhuramachandran** [enthought/pyface#297]
If you run the following script (with Mayavi from master) and with Qt5 (Python3.6 on MacOS). It shows several issues.  
```
from mayavi import mlab
mlab.test_plot3d()
mlab.show()
```
As soon as you run this we get this warning:

QWidgetWindow(0x127689ae0, name="_ToolBarClassWindow") ( QScreen(0x1014fbb10, name="Color LCD") ): Attempt to set a screen on a child window.
QWidgetWindow(0x127689ae0, name="_ToolBarClassWindow") ( QScreen(0x1014fbb10, name="Color LCD") ): Attempt to set a screen on a child window.
QWidgetWindow(0x127689f10, name="QMainWindowClassWindow") ( QScreen(0x1014fbb10, name="Color LCD") ): Attempt to set a screen on a child window.
QWidgetWindow(0x127689ae0, name="_ToolBarClassWindow") ( QScreen(0x1014fbb10, name="Color LCD") ): Attempt to set a screen on a child window.
libpng warning: iCCP: known incorrect sRGB profile
QWidgetWindow(0x127689ae0, name="_ToolBarClassWindow") ( QScreen(0x1014fbb10, name="Color LCD") ): Attempt to set a screen on a child window.

If you click on the Mayavi icon and then click on the script recording button (red button), 
Traceback (most recent call last):
  File ".../build/lib/pyface/ui/qt4/code_editor/gutters.py", line 117, in paintEvent
    block = next(block)
TypeError: 'QTextBlock' object is not an iterator

Further, it actually crashes at this point severely.  It would be great if this could be fixed before the release.  These are all not specifically mayavi related which is why I am posting it here, of course.

**Comment by corranwebster** [comment]
Which version of PyQt5 are you using? We (and other projects like matplotlib) are noticing problems with PyQt5 5.10.

Other than that, I will look  into it before the release.

**Comment by prabhuramachandran** [comment]
Hi I am using pyqt5 5.8.2-1 from the build-sandbox and with a small hand-patch. https://github.com/enthought/buildsystem/issues/1248

**Comment by corranwebster** [comment]
Thanks - I will look into what is going on here today.

**Comment by corranwebster** [comment]
Ah.  This is a 2to3 error!  The converters are seeing `block.next()` and converting it to `next(block)`.  This has been a problem in other ETS projects, but should be an easy fix.

**Comment by corranwebster** [comment]
Hmmm... we already have that fixer excluded from the 2to3 fixers: https://github.com/enthought/pyface/blob/master/setup.py#L182

How did you install pyface?

**Comment by prabhuramachandran** [comment]
Thanks! I installed from master using python setup.py develop.

More disturbing are the toolbar errors.   If you run the full Mayavi app, sometimes  the toolbar disappears, and on some other custom applications the toolbar floats out of the window when you move the window.  I know these are not easy to reproduce but I suspect those warnings need to be addressed.

It also looks like any exceptions raised result in as crash but that might be the build of Qt, I am not sure.

**Comment by corranwebster** [comment]
I just did a clean pyface install into an edm environment with `python setup.py develop` and it didn't apply the `next()` method fix as expected, so I don't know what went wrong with your install.  The correct fix for this is to move away from 2to3, but I don't think I want to attempt that before the release.

Looking at the other issues above:

- `libpng warning: iCCP: known incorrect sRGB profile` this means that there is a bad PNG file somewhere.  There were a number of these kicking around the Pyface and TraitsUI codebase.  I think they were recently fixed, but I would need to double check.  They should be fixed before the 6.0 release.
- the QScreen error has me baffled, but I haven't yet tried to reproduce. My best guess is that this may be something to do with whether the toolbars can be moved or even popped out of the parent window. We don't do anything with QScreen objects as far as I can tell, and the `_ToolBar` class which is seeing the errors is very simple: https://github.com/enthought/pyface/blob/master/pyface/ui/qt4/action/tool_bar_manager.py#L140

I will dig further.

**Comment by prabhuramachandran** [comment]
OK sorry, I will wipe out the build directory and try again afresh and get back if I run into this.  Thanks.  I will also try and spend some time on the toolbar issue and see if I can get any insight tomorrow on it.  Thanks!

**Comment by prabhuramachandran** [comment]
After I cleared out the directory and reinstalled it seems fine in that I don't see a crash.  I still get the QScreen/QWidgetWindow warnings though.  Thanks!

**Comment by corranwebster** [comment]
FWIW I couldn't reproduce the QScreen/QWidgetWarning on my machine (MacOS 10.13, pyqt5 from the Mac wheel, master of everything ETS except Traits and Envisage), but I did manage to get a couple of hard crashes:

<details>
<summary>NotImplementedError: the qt4 traitsui.qt4 backend doesn't implement tree_editor:CustomEditor</summary>

```
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/pyface-5.2.0.dev344-py3.6.egg/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/pyface-5.2.0.dev344-py3.6.egg/pyface/workbench/action/action_controller.py", line 35, in perform
    return action.perform(event)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/pyface-5.2.0.dev344-py3.6.egg/pyface/workbench/action/show_view_action.py", line 29, in perform
    ui = chooser.edit_traits(parent=self.window.control, kind='livemodal')
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traits/has_traits.py", line 1870, in edit_traits
    handler, id, scrollable, args )
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/view.py", line 448, in ui
    ui.ui(parent, kind)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/ui.py", line 234, in ui
    self.rebuild(self, parent)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/toolkit.py", line 157, in ui_livemodal
    ui_live.ui_livemodal(ui, parent)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/ui_live.py", line 46, in ui_livemodal
    _ui_dialog(ui, parent, BaseDialog.MODAL)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/ui_live.py", line 62, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/ui_base.py", line 277, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/ui_live.py", line 202, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/ui_panel.py", line 263, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/ui_panel.py", line 603, in __init__
    layout = self._add_items(content, inner)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/qt4/ui_panel.py", line 863, in _add_items
    ui, object, name, item.tooltip, None
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traitsui-5.2.0.dev397-py3.6.egg/traitsui/editor_factory.py", line 156, in custom_editor
    description=description)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/pyface-5.2.0.dev344-py3.6.egg/pyface/base_toolkit.py", line 178, in __init__
    raise NotImplementedError(msg % (toolkit, package, name))
NotImplementedError: the qt4 traitsui.qt4 backend doesn't implement tree_editor:CustomEditor
```
</details>

and

<details>
<summary>AttributeError: module 'pyface.qt.QtGui' has no attribute 'QStyleOptionTabV3'</summary>

```
Traceback (most recent call last):
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/pyface-5.2.0.dev344-py3.6.egg/pyface/ui/qt4/workbench/split_tab_widget.py", line 897, in mouseDoubleClickEvent
    self._resize_title_edit_to_current_tab()
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/pyface-5.2.0.dev344-py3.6.egg/pyface/ui/qt4/workbench/split_tab_widget.py", line 985, in _resize_title_edit_to_current_tab
    tab = QtGui.QStyleOptionTabV3()
AttributeError: module 'pyface.qt.QtGui' has no attribute 'QStyleOptionTabV3'
```
</details>

The latter looks like a problem with old API usage in the Qt backend of Workbench.  More generally, that is where we may find significant problems for Qt5 and Mayavi, as that is old, somewhat hacky code that Mayavi uses extensively.

**Comment by prabhuramachandran** [comment]
@corranwebster -- thanks for trying this out,  I was using pyqt5.8.2 from our build sandbox and when I upgraded to pyqt5 (version PyQt5-5.10.1) from PyPI, the QScreen/QWidgetWarnings are all gone.  The toolbar is no longer floating around either which is a huge relief.   So I think this ticket can be safely closed.  Thanks for your help!

**Comment by corranwebster** [comment]
No problem - take care with PyQt5-5.10, though, it seems less stable than PyQt5-5.9.

**Comment by prabhuramachandran** [comment]
Oh OK, will keep that in mind, thanks.

**Comment by gowthamikandru** [comment]
how can i hide/remove the whole toolbar in mayavi?

**Comment by Farnsworth1** [comment]
**use tvtk.pyface.api.scene** instead of **mayavi.core.ui.mayavi_scene.MayaviScene**
the following line defines the scene:
view = View(Item('scene', editor=SceneEditor(scene_class=Scene),
                     height=250, width=300, show_label=False), resizable=True)
